spring:
  application:
    name: discovery-service
  profiles:
    default: local

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
